### ISSUE TITLE
error: bad escape \p at position 257

### ISSUE THREAD

**Issue by clone95** [MartinoMensio/it_vectors_wiki_spacy#1]
Hi, I downloaded the vectors, but when I try to load them with:

`model = spacy.load('it_vectors_wiki_lg')

it gives me error:

`error: bad escape \p at position 257`

**Comment by MartinoMensio** [comment]
Hi Giacomo,

It is probably a problem due to some breaking changes in spacy>=2.1 (similar to https://github.com/explosion/spaCy/issues/3544 https://github.com/explosion/spaCy/issues/4261). I am testing on the latest version and I will update you soon.

Spacy versions:
- 2.2.4 --> error
- 2.1.0 --> error
- 2.0.5 --> working

As a temporary solution, I suggest installing spacy 2.0.18 with `pip install spacy==2.0.18`. I will recreate the model and publish a new release soon.

Thanks for trying out this model!

**Comment by clone95** [comment]
Thanks, but the useful thing was to use it for the "pretrain" command, feature present from 2.1
 My use case is the following:
I have 400 long Italian documents, tagged with NER entities and my final goal is to train a good NER on these docs
I wanted to pretrain the word vectors on these 400 docs in an unsupervised fashion. Then train the NER model with these vectors (in the tok2vec component) . So I need a Spacy version > 2.2
Here they inserted this feature:
https://explosion.ai/blog/spacy-v2-1

**Comment by MartinoMensio** [comment]
I've uploaded the new release of the model: https://github.com/MartinoMensio/it_vectors_wiki_spacy/releases/tag/v1.0.1

Try installing with `pip install https://github.com/MartinoMensio/it_vectors_wiki_spacy/releases/download/v1.0.1/it_vectors_wiki_lg-1.0.1.tar.gz `

I've tested on SpaCy 2.2.4 and it loads successfully in my environment. Let me know if the new release solves your problem.

**Comment by clone95** [comment]
Very nice it works indeed! 
Thanks very much for the stunningly fast support! 🥇

**Comment by MartinoMensio** [comment]
Thank you indeed! :)
